import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="border-b border-solid border-gray-500 pb-2">
          <Link href="/">🏠</Link>
        </nav>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="z-10 w-full items-center justify-between">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
